### ISSUE TITLE
toString() does not work as it should do

### ISSUE THREAD

**Issue by Computershik73** [greyson/j2me-json#1]
in /test/org/json/me/test/Test.java
on line 65, if I use form.append(jj.toString()) it will write string@hexstring , but not JSON's string representation. Why?
And 
> >
 myString = new JSONStringer()
     .object()
         .key("JSON")
         .value("Hello, World!")
     .endObject()
     .toString();
which produces the string  {"JSON":"Hello, World!"}
< <
Doesn't produce it.
I have set project's compatibility to Java 1.4, otherwise Proguard doesn't want to work

**Comment by greyson** [comment]
Since there is no `form` in the test, I suspect that your code is in error.
